# Generated by Django 2.1.1 on 2018-10-25 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zappyapp', '0002_auto_20181025_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_address', models.CharField(max_length=400)),
                ('mobile', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delievery_address', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='pname',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_choice',
            field=models.CharField(choices=[('rte', 'Ready To Eat'), ('rtc', 'Ready To Cook')], default='rte', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zappyapp.Product'),
        ),
    ]
