# Generated by Django 2.1.1 on 2018-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0003_auto_20181025_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='cat_choice',
            field=models.CharField(choices=[('rte', 'Ready To Eat'), ('rtc', 'Ready To Cook')], default='rte', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
