# Generated by Django 2.1.1 on 2018-10-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0006_auto_20181025_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Products/default.png', upload_to='Products'),
        ),
    ]
