# Generated by Django 2.1.1 on 2018-10-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0008_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Customers/profile_pics'),
        ),
    ]
