# Generated by Django 2.1.1 on 2018-10-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0010_auto_20181026_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='images',
        ),
    ]
