# Generated by Django 2.1.1 on 2018-10-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zappyapp', '0011_auto_20181026_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Products/default1.jpg', upload_to='Products'),
        ),
    ]
